//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 08:53:03 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.democxfapp.com/democxfapp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.democxfapp.democxfapp;
